# Generated by Django 6.0.2 on 2026-02-24 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_don_hang', models.CharField(max_length=20, unique=True, verbose_name='Mã đơn hàng')),
                ('ho_ten_nguoi_nhan', models.CharField(max_length=100, verbose_name='Họ tên người nhận')),
                ('so_dien_thoai_nhan', models.CharField(max_length=15, verbose_name='Số điện thoại nhận')),
                ('dia_chi_giao_hang', models.TextField(verbose_name='Địa chỉ giao hàng')),
                ('phuong_thuc_giao', models.CharField(choices=[('nhan_tai_cua_hang', 'Nhận tại cửa hàng'), ('giao_tan_noi', 'Giao tận nơi')], default='giao_tan_noi', max_length=20, verbose_name='Phương thức giao')),
                ('phuong_thuc_thanh_toan', models.CharField(choices=[('tien_mat', 'Tiền mặt'), ('chuyen_khoan', 'Chuyển khoản'), ('the_ngan_hang', 'Thẻ ngân hàng')], default='tien_mat', max_length=20, verbose_name='Phương thức thanh toán')),
                ('trang_thai', models.CharField(choices=[('cho_xac_nhan', 'Chờ xác nhận'), ('da_xac_nhan', 'Đã xác nhận'), ('dang_dong_goi', 'Đang đóng gói'), ('ban_giao_van_chuyen', 'Bàn giao vận chuyển'), ('dang_giao', 'Đang giao hàng'), ('da_giao', 'Đã giao hàng'), ('huy', 'Đã hủy')], default='cho_xac_nhan', max_length=25, verbose_name='Trạng thái')),
                ('tong_tien_san_pham', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Tổng tiền sản phẩm')),
                ('phi_giao_hang', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Phí giao hàng')),
                ('giam_gia', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Giảm giá')),
                ('ma_van_don', models.CharField(blank=True, max_length=100, verbose_name='Mã vận đơn')),
                ('ghi_chu', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('cua_hang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='don_hangs', to='stores.cuahang', verbose_name='Cửa hàng')),
                ('khach_hang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='don_hangs', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'ordering': ['-ngay_tao'],
            },
        ),
        migrations.CreateModel(
            name='ChiTietDonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField(verbose_name='Số lượng')),
                ('gia_tai_thoi_diem', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá tại thời điểm đặt')),
                ('san_pham', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.sanpham', verbose_name='Sản phẩm')),
                ('don_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiets', to='orders.donhang', verbose_name='Đơn hàng')),
            ],
            options={
                'verbose_name': 'Chi tiết đơn hàng',
                'verbose_name_plural': 'Chi tiết đơn hàng',
            },
        ),
        migrations.CreateModel(
            name='LichSuTrangThai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trang_thai_cu', models.CharField(max_length=25, verbose_name='Trạng thái cũ')),
                ('trang_thai_moi', models.CharField(max_length=25, verbose_name='Trạng thái mới')),
                ('ghi_chu', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('thoi_gian', models.DateTimeField(auto_now_add=True)),
                ('don_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_trang_thais', to='orders.donhang', verbose_name='Đơn hàng')),
                ('nguoi_thuc_hien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
            ],
            options={
                'verbose_name': 'Lịch sử trạng thái',
                'verbose_name_plural': 'Lịch sử trạng thái',
                'ordering': ['-thoi_gian'],
            },
        ),
        migrations.CreateModel(
            name='GioHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField(default=1, verbose_name='Số lượng')),
                ('ngay_them', models.DateTimeField(auto_now_add=True)),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gio_hangs', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.sanpham', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Giỏ hàng',
                'unique_together': {('nguoi_dung', 'san_pham')},
            },
        ),
    ]
