# Generated by Django 6.0.2 on 2026-04-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lichsutrangthai',
            name='trang_thai_cu',
            field=models.CharField(choices=[('cho_xac_nhan', 'Chờ xác nhận'), ('da_xac_nhan', 'Đã xác nhận'), ('dang_dong_goi', 'Đang đóng gói'), ('ban_giao_van_chuyen', 'Bàn giao vận chuyển'), ('dang_giao', 'Đang giao hàng'), ('da_giao', 'Đã giao hàng'), ('huy', 'Đã hủy')], max_length=25, verbose_name='Trạng thái cũ'),
        ),
        migrations.AlterField(
            model_name='lichsutrangthai',
            name='trang_thai_moi',
            field=models.CharField(choices=[('cho_xac_nhan', 'Chờ xác nhận'), ('da_xac_nhan', 'Đã xác nhận'), ('dang_dong_goi', 'Đang đóng gói'), ('ban_giao_van_chuyen', 'Bàn giao vận chuyển'), ('dang_giao', 'Đang giao hàng'), ('da_giao', 'Đã giao hàng'), ('huy', 'Đã hủy')], max_length=25, verbose_name='Trạng thái mới'),
        ),
    ]
