# Generated by Django 6.0.2 on 2026-02-24 16:35

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuaHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200, verbose_name='Tên cửa hàng')),
                ('ma_cua_hang', models.CharField(max_length=20, unique=True, verbose_name='Mã cửa hàng')),
                ('dia_chi', models.TextField(verbose_name='Địa chỉ')),
                ('quan_huyen', models.CharField(max_length=100, verbose_name='Quận/Huyện')),
                ('tinh_thanh', models.CharField(max_length=100, verbose_name='Tỉnh/Thành phố')),
                ('so_dien_thoai', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('vi_tri', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Vị trí (tọa độ)')),
                ('gio_mo_cua', models.TimeField(verbose_name='Giờ mở cửa')),
                ('gio_dong_cua', models.TimeField(verbose_name='Giờ đóng cửa')),
                ('ngay_lam_viec', models.CharField(default='Thứ 2 - Chủ nhật', max_length=100, verbose_name='Ngày làm việc')),
                ('dien_tich', models.FloatField(blank=True, null=True, verbose_name='Diện tích (m²)')),
                ('so_luong_nhan_vien', models.IntegerField(default=0, verbose_name='Số nhân viên')),
                ('dang_hoat_dong', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cửa hàng',
                'verbose_name_plural': 'Cửa hàng',
                'ordering': ['ten'],
            },
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_nhan_vien', models.CharField(max_length=20, unique=True, verbose_name='Mã nhân viên')),
                ('chuc_vu', models.CharField(choices=[('quan_ly', 'Quản lý cửa hàng'), ('thu_ngan', 'Thu ngân'), ('ban_hang', 'Nhân viên bán hàng'), ('kho', 'Nhân viên kho'), ('giao_hang', 'Shipper')], max_length=20, verbose_name='Chức vụ')),
                ('ngay_vao_lam', models.DateField(verbose_name='Ngày vào làm')),
                ('luong_co_ban', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Lương cơ bản (VNĐ)')),
                ('dang_lam_viec', models.BooleanField(default=True, verbose_name='Đang làm việc')),
                ('cua_hang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nhan_viens', to='stores.cuahang', verbose_name='Cửa hàng')),
                ('nguoi_dung', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nhan_vien', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Nhân viên',
                'verbose_name_plural': 'Nhân viên',
            },
        ),
        migrations.CreateModel(
            name='CaLamViec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thu_trong_tuan', models.IntegerField(choices=[(0, 'Thứ 2'), (1, 'Thứ 3'), (2, 'Thứ 4'), (3, 'Thứ 5'), (4, 'Thứ 6'), (5, 'Thứ 7'), (6, 'Chủ nhật')], verbose_name='Thứ trong tuần')),
                ('gio_bat_dau', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('gio_ket_thuc', models.TimeField(verbose_name='Giờ kết thúc')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ca_lam_viecs', to='stores.nhanvien', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Ca làm việc',
                'verbose_name_plural': 'Ca làm việc',
                'unique_together': {('nhan_vien', 'thu_trong_tuan', 'gio_bat_dau')},
            },
        ),
    ]
