# Generated by Django 6.0.2 on 2026-02-24 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(unique=True)),
                ('mo_ta', models.TextField(blank=True, verbose_name='Mô tả')),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='danh_muc/')),
                ('thu_tu', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh mục',
                'ordering': ['thu_tu', 'ten'],
            },
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('ma_san_pham', models.CharField(max_length=50, unique=True, verbose_name='Mã sản phẩm')),
                ('mo_ta_ngan', models.CharField(blank=True, max_length=300, verbose_name='Mô tả ngắn')),
                ('mo_ta_chi_tiet', models.TextField(blank=True, verbose_name='Mô tả chi tiết')),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='san_pham/')),
                ('gia_ban', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá bán (VNĐ)')),
                ('gia_nhap', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá nhập (VNĐ)')),
                ('gia_khuyen_mai', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Giá khuyến mãi')),
                ('thuong_hieu', models.CharField(blank=True, max_length=100, verbose_name='Thương hiệu')),
                ('xuat_xu', models.CharField(blank=True, max_length=100, verbose_name='Xuất xứ')),
                ('trong_luong', models.FloatField(blank=True, null=True, verbose_name='Trọng lượng (g)')),
                ('dang_ban', models.BooleanField(default=True, verbose_name='Đang bán')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('danh_muc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='san_phams', to='products.danhmuc', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
                'ordering': ['-ngay_tao'],
            },
        ),
        migrations.CreateModel(
            name='TonKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField(default=0, verbose_name='Số lượng tồn')),
                ('so_luong_toi_thieu', models.IntegerField(default=5, verbose_name='Tồn kho tối thiểu')),
                ('vi_tri_ke', models.CharField(blank=True, max_length=50, verbose_name='Vị trí kệ')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('cua_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ton_khos', to='stores.cuahang', verbose_name='Cửa hàng')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ton_khos', to='products.sanpham', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Tồn kho',
                'verbose_name_plural': 'Tồn kho',
                'unique_together': {('san_pham', 'cua_hang')},
            },
        ),
        migrations.CreateModel(
            name='LichSuKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai', models.CharField(choices=[('nhap', 'Nhập kho'), ('xuat', 'Xuất kho'), ('dieu_chinh', 'Điều chỉnh')], max_length=15, verbose_name='Loại')),
                ('so_luong_thay_doi', models.IntegerField(verbose_name='Số lượng thay đổi')),
                ('so_luong_truoc', models.IntegerField(verbose_name='Số lượng trước')),
                ('so_luong_sau', models.IntegerField(verbose_name='Số lượng sau')),
                ('ghi_chu', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('nguoi_thuc_hien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
                ('ton_kho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_sus', to='products.tonkho', verbose_name='Tồn kho')),
            ],
            options={
                'verbose_name': 'Lịch sử kho',
                'verbose_name_plural': 'Lịch sử kho',
                'ordering': ['-ngay_tao'],
            },
        ),
    ]
