# Generated by Django 6.0.2 on 2026-04-20 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HinhAnhSanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anh', models.ImageField(upload_to='san_pham/gallery/', verbose_name='Ảnh kèm theo')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_sach_anh', to='products.sanpham', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Hình ảnh sản phẩm',
                'verbose_name_plural': 'Hình ảnh sản phẩm',
            },
        ),
    ]
